basePath: /
definitions:
  dto.APIResponse:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.CreateScopeRequest:
    properties:
      scope_name:
        type: string
    required:
    - scope_name
    type: object
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      scopes:
        items:
          type: string
        type: array
      username:
        type: string
    required:
    - email
    - password
    - scopes
    - username
    type: object
  dto.DeleteRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  dto.UpdateScopeRequest:
    properties:
      is_added:
        type: boolean
      scopes:
        type: string
      user_id:
        type: string
    required:
    - scopes
    - user_id
    type: object
host: localhost:8085
info:
  contact: {}
  description: Container Management System API
  title: VCS SMS API
  version: "1.0"
paths:
  /scopes/create:
    post:
      consumes:
      - application/json
      description: Create a scope
      parameters:
      - description: Scope creation request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateScopeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: New scope created successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      summary: Create a new scope
      tags:
      - scopes
  /users/create:
    post:
      consumes:
      - application/json
      description: Create a user
      parameters:
      - description: User creation request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: New user created successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      summary: Create a new user
      tags:
      - users
  /users/delete:
    delete:
      consumes:
      - application/json
      description: Remove a user from the system (admin only)
      parameters:
      - description: User ID to delete
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User deleted successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Delete a user
      tags:
      - users
  /users/update/scope:
    put:
      consumes:
      - application/json
      description: Update permission scope of a user (admin only)
      parameters:
      - description: User ID, scopes, and whether to add or remove
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateScopeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Scope updated successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Update a user's scope
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
